### PR TITLE
fix(table): fixed layout of table-header items

### LINKED ISSUE #47: Table: HeaderActions are not right-aligned if [filterable]="false"
If you set header-actions and disable the searchbox, the header-actions are placed right after the sorting.

grafik

Expected: The header-actions should always be right-aligned

### PR DESCRIPTION
**Pull request by 6rayWolf**
fix #47

### CODE REVIEW

**Comment by saithis** [comment]
Hmm, with this fix you could also remove the "margin: auto;" from .ps-table-header__search.
With sorting this wouldn't change anything, but when the sorting is hidden, the filter will be left aligned.

File: projects/components/table/src/subcomponents/table-header.component.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ import { IPsTableSortDefinition } from '../models';
         display: flex;
         flex-wrap: wrap;
         align-items: flex-end;
+        justify-content: space-between;
```
Comment (Yirica) [inline projects/components/table/src/subcomponents/table-header.component.ts]: With this change, "margin: auto" of "ps-table-header__search" is obsolete
